### ISSUE TITLE
Car sometimes couldn’t stop in time for late detected lights

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#114]
During Udacity simulator and site  testing, the red light detection was late sometimes so the car judged that it was too late to slow down in time based on the estimated minimum stopping distance. Some improvement to the estimated stopping distance may be needed to allow more chance to stop for late traffic light detections.

**Comment by teeekay** [comment]
After running tests, it looks like we can't get much out of this.  Shorter distances will result in higher deceleration rates, that can be magnified in dbw response.  It looks like use of abs_max_jerk of 6 is suitable for calculating a stop distance that won't exceed jerk or acceleration limits of 10 in the simulator from speeds of 40 or 60 km/hr.

**Comment by teeekay** [comment]
On last test it was about 1 m shorter.

**Comment by teeekay** [comment]
```get_min_stopping_distance found shortest Distance of 3.387m to decelerate with start_jerk=-5.789, end_jerk=-3.579 ,from v=2.667, a=0.000 to v=1.250, a=-0.100 in 2.540s - Took 0.0002s to calc```

**Comment by edufford** [comment]
Ok, every bit adds up though so all your improvements definitely help.

**Comment by edufford** [comment]
Improvements have been implemented, closing this issue.
