### ISSUE TITLE
Set up development environments

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#2]
All members set up development environments and check successful build of base source and communication with simulator.

**Comment by edufford** [comment]
My environment is ready running Ubuntu+ROS on Mac Mini and ssh tunnel to Simulator on MacBook Pro.  I was able to build and run base project and confirm operation with simulator.

**Comment by meenunat** [comment]
My environment is ready with Ubuntu + ROS. I was able to build base project and connect to the simulator.

**Comment by teeekay** [comment]
My environment is ready with Ubuntu + ROS. I was able to build base project and believe that simulator connection is successful.

**Comment by dinoboy197** [comment]
Native Ubuntu plus + ROS is working over here. Able to connect to simulator and all is well.

**Comment by meenunat** [comment]
I did a git pull to the latest merged master code. I also did the following for rqt plugin: 
sudo apt-get update
sudo apt-get install ros-kinetic-rqt-multiplot
rqt --force-discover

There was no error for the first 2 commands - when I force discover rqt with simulator running and roslaunch in separate terminal- I see a pop up window, but it is empty window 

Am I missing anything here ? can anyone please help?

Also - I want to check the code merged so far - simulator (test lot)/roslaunch works fine - but should I expect way points bbeing printed /shown somewhere ? How is everyone running the code ?

**Comment by dinoboy197** [comment]
> There was no error for the first 2 commands - when I force discover rqt with simulator running and roslaunch in separate terminal- I see a pop up window, but it is empty window

I also had this situation on Ubuntu Linux. What I realized was that the menu does not appear in the pop up window, but up in the main toolbar. If you're on Linux, try looking for the menu there.

> Also - I want to see how the code merged so far works - can this be done without vis ?- simulator (test lot)/roslaunch works fine - but should I expect way points being printed /shown somewhere 
 How is everyone running the code ?

The readme has [instructions for downloading the simulator and launching it](https://github.com/team-fusionx/CarND-Capstone#native-installation).

Then, check out the [usage](https://github.com/team-fusionx/CarND-Capstone#usage) section of the README file. It will help you start up the codebase.

**Comment by meenunat** [comment]
Thanks Taylor - the simulator does connect to ROS. with the latest branch - should I expect waypoints getting updated /printed in any window? since I am dont see the car moving / any waypoints output. 

Yes, I am using Ubuntu Linux. I will check for the menu bar.

**Comment by edufford** [comment]
Yes, the waypoints should show up in the simulator as a green line in front of the car, just like in the MPC project.  If you have RViz set up like shown in the README, you can also see the green line of waypoints in the visualization.  The car starts in Manual driving mode so it won't move on its own unless you uncheck that box in the top left of the simulator.  If you can open the RQT layout I made, you can also check the /final_waypoints topic in the topic list and see if it is transmitting at 30Hz as intended.

**Comment by meenunat** [comment]
The waypoints does show up once I switch from manual mode (I didnt notice that - My bad) and with the menu option I am able to load Rqt. Thanks Taylor and Effendi +1:

**Comment by shrikondra** [comment]
@edufford  
Native Ubuntu + ROS is working now for me. 
Able to connect to simulator and seeing the green waypoints after unchecking the manual mode.
RViz set up also done.
Started today (12th Mar) with the Classifier task.

**Comment by edufford** [comment]
@shrikondra Awesome!  Thanks for the update, I think we are all up and running now so I’ll close this issue.
