### ISSUE TITLE
Waypoint Updater: Investigate using JMT for setting speed profile of waypoints

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#23]
Using JMT to calculate the speed profiles may result in automatically smoothing the acceleration/jerk and also may be more convenient when updating a profile in the middle of an accel pattern to maintain state continuity.  Let's investigate implementing this during the 2nd pass.

**Comment by edufford** [comment]
JMT speed profiles has been implemented by merged PR #46, so this can be closed.  Further development will be done with integration testing (issue #25) to check the planner's behavior with real transients from the traffic light state changes, so another task can be opened later if improvements are needed.

**Comment by edufford** [comment]
Sorry, I just remembered a few of the minor changes that I requested on PR #46, so we can close this after those are implemented.

**Comment by teeekay** [comment]
I think we might need to develop new code to merge accel and decel curves which would break the process into 2 steps.  1) "stop_accelerating" find the shortest distance to safely reduce acceleration to 0 without exceeding velocity or jerk limits, and then 2)"slowdown" build the regular slowdown curve from peak velocity, acceleration = 0.

Otherwise the jerk minimizing code tends not to reduce acceleration enough at the beginning of the curve and it can produce velocities that exceed our limits (which would end up being limited in the waypoint but would produce bad jerk / accel values).  I don't think this is an issue going the other way (from decel to accel) , but I will need to run simulations to see if it might cause the car to stop/go backwards.

I think creation of a simulation to test transitioning at each waypoint of both speedup and slowdown curves would be an interesting exercise. and could assist with developing logic to determine actual safe/comfortable stopping distance at any point in the speed/acceleration profile.  

Any suggestions or thoughts?

**Comment by edufford** [comment]
I think as long as the JMT is set with kinematically feasible distance and time like you are doing, the velocities should stay within the start/end values so it should be ok.  Jerk should also always be ok because it should always be minimized.  Accelerations are much harder to control and keep within limits though.

One way might be to implement a multi-step JMT generation with some calculated adjustment factors in-between.  For example as a way to switch between default gradual accel and max accel profiles:

1. Calculate the JMT for stopping distance based on the default accel rate and accel/time extension factors.  If we are farther than this distance, there is enough space so use this JMT.

2. If we are closer than this distance, recalculate the JMT for min stopping distance based on the max accel rate and 1.0 extension factors (this JMT peak accel should actually exceed the limit because the accel distance is calculated by a formula that assumes constant accel rate). Check the JMT profile to find the peak accel rate it generated and then calculate an adjustment factor = (max accel rate / peak accel rate) and recalculate JMT with accel rate reduced by this adjustment factor to hopefully result in a JMT profile that actually stays close within the max accel rate.

3. We can then wait until the car gets to this min stopping distance to start following the JMT, or we can do an additional step that tries to calculate an intermediate level accel JMT curve in between 1 and 2, maybe by a linear interpolation between the accel rates based on the distance between the default and min stopping distances.  Need to think about this one more.

Another way would be to do a more iterative JMT recalculation loop starting from the min stopping distance JMT calculated in 2 above, and then iteratively reduce the accel rate and extension factors until the stopping distance reaches the car's current distance from the light.

Either way, we also need the info of min stopping distance at max accel rate to judge if we just can't stop at this light and need to run through it.

What do you think?

**Comment by edufford** [comment]
I think as long as we can adjust the JMT for shorter distances while keeping its accel within the max limit, we shouldn’t need to split up any special states or break up the start to end profiles so the JMT can keep connecting the curves smoothly.  This should be able to handle all the different state switching cases I think, but it definitely would be nice to prototype this offline like with your trajectory test code.

**Comment by teeekay** [comment]
I will try to run some scenarios this evening to investigate.  I agree we need to determine minimum stopping distance to make stop / run yellow light decisions.  When using JMT, I have not found a "trivial" way to solve for this because acceleration change is not linear during the process.

**Comment by teeekay** [comment]
Reading this through now as it seems relevant
https://www.researchgate.net/publication/279479049_Chauffeur_braking

**Comment by edufford** [comment]
That’s a pretty interesting paper but I think it basically confirms that using JMT from initial state to the stop is the most comfortable. Their special case 2 for overbraking to a stopping point slightly farther than necessary probably won’t apply to our case since the light positions are fixed and if it changes red to green, we will not have to stop again until the next light far away.  Unfortunately they didn’t seem to address the opposite case where the stopping point becomes closer than originally planned for, which is what we really need.

**Comment by edufford** [comment]
The simplest way to deal with this would be to only set JMT curves for the worst case stopping distance and max accel rates, and if distance is shorter then just run through the light.  Unfortunately this would not be comfortable for the normal case so I think we can find a way to switch or blend between the normal comfort case and the short stopping distance case by just adjusting the target accel rate and extension ratios.

You already have a really good base algorithm that covers the normal comfort case, so something with minimal simple changes would be best for this project if possible, even if it doesn’t cover all transient conditions perfectly.  Good luck with your tests and let me know if I can do anything to help!

**Comment by edufford** [comment]
By the way, keep in mind that the real drive on Udacity’s test lot has speeds and distances so small that there isn’t really enough room for much of any transition logic to work.  Try replaying the Udacity successful light detection bag and watch the images and speed profile in RQT to see it.

A lot of this logic is mainly for the simulation and thinking about if the car would drive in more realistic conditions, but it needs to also work on Udacity’s unrealistic tiny test course.

**Comment by teeekay** [comment]
I worked this weekend on finding the shortest acceptable stopping distance. I will try to make a commit with this, tonight (although there will still need to be logic for not stopping).  Then I will move to looking at the rosbag.

**Comment by edufford** [comment]
These additional improvements to the JMT calculation to account for minimum stopping distances and changing accel direction within a target jerk limit are being implemented in PR #64.

**Comment by edufford** [comment]
Further improvements have been implemented in PR #75.  Closing this issue and moving to testing and debugging.
