### ISSUE TITLE
DBW: Investigate using MPC for steering control

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#24]
Current pure pursuit + yaw controller algorithm may not always steer smoothly and MPC may be able to provide a more natural steering pattern.  Let's investigate if MPC can be implemented to do the steering during the 2nd pass.

**Comment by edufford** [comment]
This issue is low priority since simply retuning the pure pursuit following threshold values seems to help improve the steering response so far.  After further detailed testing, if some steering hunting is found, then we can look into MPC for further improvement if needed.

**Comment by dinoboy197** [comment]
I agree; the PID controller mechanisms seem to do a fine job so far. I don't see the need to do a complete overhaul for this project.

**Comment by edufford** [comment]
Closing this for now, since it's not likely we'll switch to MPC.
