### ISSUE TITLE
Testing: Confirm correct operation on sim highway track 1

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#25]
Save ROS bag data for one complete lap of simulator highway track 1 and analyze data to confirm correct operation of all features.

Confirm Udacity's checkpoints:

* Smoothly follow waypoints in the simulator.

* Respect the target top speed set for the waypoints' twist.twist.linear.x in waypoint_loader.py. Be sure to check that this is working by testing with different values for kph velocity parameter in /ros/src/waypoint_loader/launch/waypoint_loader.launch. If your vehicle adheres to the kph target top speed set here, then you have satisfied this requirement.

* Stop at traffic lights when needed.

* Stop and restart PID controllers depending on the state of /vehicle/dbw_enabled.

* Publish throttle, steering, and brake commands at 50hz.

* Launch correctly using the launch files provided in the capstone repo.

**Comment by edufford** [comment]
For the checkpoint:

- Respect the target top speed set for the waypoints' twist.twist.linear.x in waypoint_loader.py. Be sure to check that this is working by testing with different values for kph velocity parameter in /ros/src/waypoint_loader/launch/waypoint_loader.launch. If your vehicle adheres to the kph target top speed set here, then you have satisfied this requirement.

I read on Slack somewhere that they will try reducing the velocity parameter from 40 kph to 20 kph, so this is a good number to try.

**Comment by meenunat** [comment]
With RC2 version:

The car was able to run through the simulation track 1 - with acceleration not exceeding 10 m/s^2 and jerk not exceeding 10 m/s^3.

I have tried 10 kph and 60kph - the simulator speed changed to 6 Mph for velocity param = 10; the speed was approx ~23 for a value of 40 and approx ~35 for a value of 60 kph. But do notice the car going pass the lights (yellow/red) if the distance is too short to stop.

The car did stop at the lights when it is red **except when the distance is too short to stop.**

Toggling manual switch made the car to go off the track but enabling it retrieves it back to the correct course.

The throttle, steering, and brake commands are published at 49-51hz

The launch files are enabled and working correctly.

**Comment by meenunat** [comment]
With the fix to update waypoint when last state is Yellow and the current state is yelllow , the car is able to stop at the red lights. I didnt see it driving pass RED light when velocity is set to 15/60 kph. In either case the jerl was AccT was ~7 m/s^2 (worst case) and Jerk was ~1 m/s^3. The car driving pass the yellow seems to be expected - so I guess we are good on that front. 

PR TL detection: updated the condition to update wp. @edufford @teeekay - can you please cross verify the results at your side with the PR?

**Comment by edufford** [comment]
After the latest fix, it works well from my testing.  I didn't see any issues.

**Comment by edufford** [comment]
Initial release v1.0 is now ready for submission.  Closing this issue.
