### ISSUE TITLE
Testing: Confirm correct operation on sim church lot track 2

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#26]
Save ROS bag data for one complete loop of simulator church lot track 2 and analyze data to confirm correct operation of all features.

This track doesn't have camera images or a stop light, so we just need to confirm that the controllers can steer the car sharply enough in this tight course and that it accelerates/decelerates smoothly.  We may need to manually set some waypoint velocity targets to simulate a stop light.

**Comment by edufford** [comment]
@meenunat The waypnt_updater.py file now has a test mode flag, so if you set `self.testing = True` and then run the simulator track 2, it will manually set a stop light waypoint to stop at and then accelerate from in the middle of the waypoint route.  We can try taking one base data set with this flag = False, and then another data set with it = True to check both cases.

**Comment by meenunat** [comment]
The car was able to stop if testing is set to true. It was able to drive around the track without any jerk/acceleration issues for testing set to true/false.

**Comment by meenunat** [comment]
With RC2 Version: when the car stops (with testing enabled) I noticed the AccT goes > 10m/s^2. With testing set to False - dont see the issue.

**Comment by edufford** [comment]
I think this is due to the stopping point being in the middle of the sharp turn combined with the simulator's very bumpy road surface and poor handling of low speed area.  The target speed profile and throttle/brake controls look fine, so I don't think we need to change our controls for this issue.

**Comment by edufford** [comment]
Initial release v1.0 is now ready for submission.  Closing this issue.
