### ISSUE TITLE
Testing: Confirm traffic light detection using real camera images from ROS bag playback

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#27]
Confirm that traffic light detection/classification works correctly using real camera images from ROS bag playback.

Udacity provided a couple ROS bags, but we may also want to try some recordings from previous teams' test runs for more sample sizes.

**Comment by edufford** [comment]
Sounds good.  With output="log" (this is actually the default for all nodes if no output is specified in the launch file), rospy.loginfo will not output to the screen but it should output to the node's .log file in `~/.ros/log/(folder generated for the run)` and also should be visible in real-time by watching the `/rosout` topic in RQT Console which can be filtered by Node.

**Comment by meenunat** [comment]
This seems to be okay for RC2 a well.

**Comment by edufford** [comment]
Initial release v1.0 is now ready for submission.  Closing this issue.
