### ISSUE TITLE
DBW: Tune PID controller for smooth accel/decel commands on sim and Udacity ROS bag

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#28]
Tune PID controller parameters and limits to ensure smooth accel/decel commands on both the simulator and during ROS bag playback with Udacity's provided test run.

Especially need to check throttle and brake command scaling differences between sim and Carla.  May need to consider using a % based system instead of absolute in case of big response difference.

**Comment by dinoboy197** [comment]
Thanks for adding this. Sounds good!

**Comment by edufford** [comment]
I added some links to the wiki for some Dataspeed DBW spec documents that may help decide the right throttle, steering, brake actuation command settings for Carla:
https://github.com/team-fusionx/CarND-Capstone/wiki#twist-controllerdrive-by-wire-dbw

**Comment by edufford** [comment]
Also, some special logic may be needed for smooth brake apply and hold near a stop condition with target speed 0 m/s.  Usually vehicle speed signals are not reliable or precise at less than 1 or 2 kph due to slow rotation of the sensor encoders so some manual control and rate limiting may be needed.

**Comment by edufford** [comment]
@dinoboy197 I realized that one benefit of the Dataspeed controller architecture was that it split out a calculation for target acceleration that could be passed to the brake command torque directly by (*m*wr).  However, if we stick with the simpler and more easily tuned direct PID control, I think we need to split the throttle PID controller and the brake PID controller, with some logic to switch between them.  I think the brake controller needs different gains to output brake torque since the scale (0-3412 Nm) and vehicle response is quite different from the throttle (0-1 percentage).  After the brake PID controller is split and tuned, then we can also add the manual brake holding torque to keep the vehicle stopped at zero speed.  Could you look into implementing this as the next step for the DBW control?

**Comment by dinoboy197** [comment]
Yep, that should be easy to implement. I did also realize that throttle and brake have different responses after implementing the Dataspeed controller! :)

**Comment by dinoboy197** [comment]
Beginning ROS bag testing now.

**Comment by edufford** [comment]
Logic is implemented, now mainly testing and tuning so moving this issue's milestone to 3rd Pass.

**Comment by edufford** [comment]
DBW tweaks and tuning has been implemented in PR #87.  Closing this issue.
