### ISSUE TITLE
DBW: Implement PID to drive to waypoints

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#4]
Implement simple PID controllers to get car to roughly move toward waypoints with dummy target speeds.

**Comment by edufford** [comment]
Let's also implement dynamic_reconfigure to be able to tune PID parameters on the fly, following example from waypoint_updater PR #18.

**Comment by edufford** [comment]
@dinoboy197 I just saw that there is a control diagram that Dataspeed uses for their DBW system that is a little different than our PID control.  Check out the 3.5.1 Speed Controller section of their [README.pdf](https://bitbucket.org/DataspeedInc/dbw_mkz_ros/raw/ecfb61cbad05e06d5de0d6a971c63c955230a982/README.pdf).  We may want to try implementing their architecture since it's proven on the real car.  What do you think?

**Comment by dinoboy197** [comment]
Very interesting. Will give it a try!

**Comment by dinoboy197** [comment]
Driving to waypoints is completed. Additional improvements are already logged in different issues, so I'm closing thisone.
