### ISSUE TITLE
TL Detection: Pass-through ground truth logging

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#45]
TL ground truth pass-through was successfully implemented and can also be triggered by manually publishing dummy image topic messages, but currently continuously logs light state and stop line info.  Please modify the rospy.loginfo commands to only output the next light's state and stop line waypoint number when it has changed to simplify the logs for future debugging.  Also, after the TL classifier is implemented, we may still want the ground truth status to be able to be logged as info for comparison to the classifier output.

**Comment by meenunat** [comment]
Need one clarification on the comment regarding -“ Also, after the TL classifier is implemented, we may still want the ground truth status to be able to be logged as info for comparison to the classifier output“-currently the way the implementation is- once the classifier is implemented it will call another function to process and not the current function. Since ground truth data is consuming the data from traffic_light_config yaml file. If we are just trying to print the site/sim configuration yaml file- I can print that all first. Is that the requirement?

**Comment by edufford** [comment]
I was thinking that once we have the actual classifier implemented, it will start making the light status judgments, but to see in the logging if those judgments were correct or delayed from the actual ground truth state of the lights, it would be helpful to have the ground truth state of the next light also printed out to the log as the current pass-through logic does so we can compare as a reference to see the accuracy of the classifier.  With the current function switching, the pass through will get disabled, so we may have to change the switching logic or split up the pass through functions so that the logging portion can still be called by the real classifier logic and only the actual publishing of the ground truth state would get switched off.  Does that make sense?

Also, the data from the yaml files that contains the light and stop line position coordinates can still be used for the real autonomous operation drive, only the state of the light's color which the simulator passes as ground truth can not be used.  This means that even when the car is using the camera images for the light state detection, we still need to link that detection with the known position coordinates of the lights from the yaml file to decide which waypoint ID should be sent when the state is red.  I think the logic that you made for the ground truth pass through that decides the waypoint ID should still be used even after switching operation back to using the camera image classifier.

**Comment by meenunat** [comment]
Make sense - will try and get back on this if I have further questions.

**Comment by meenunat** [comment]
Merged code - Closing the issue. Need to look into the error mentioned in #55 issue.

**Comment by meenunat** [comment]
Merged the code #58. Closing the issue.
