### ISSUE TITLE
TL Detection: Pass-through ground truth data

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#5]
Implement a mode switch to pass-through ground truth data for traffic light status.

**Comment by edufford** [comment]
Notes about possible implementation:

1. Find the nearest traffic light that should be visible ahead of the car’s position using get_closest_waypoint() to convert each known light’s position (in self.lights) and the car’s position to closest waypoint indices.  Then, the light index that is closest and greater than the car’s index in the waypoint index order is the light that is ahead of the car.  However, the car needs to stop at the stop line in front of the light, so you would have to find the corresponding stop line location (already loaded in stop_line_positions variable) to that light, and then get_closest_waypoint() again to the stop line’s (x,y) coord.  This waypoint index would be the output if the light is red.
2. Use camera image to classify the light status.

For step 1, I think the waypoint indexing idea is a little strange, so I would just use simple geometery and the raw (x,y,heading) coords of the car and each light in self.lights to find if a light is close enough to be visible and within heading angle range to be visible.  If a light ahead is found, find the corresponding stop line location and then use that stop line’s (x,y) coord to find the closest waypoint index.

Then for step 2, just look up the corresponding light’s status in the ground truth data for now and if it is red, pass the index of the closest waypoint to the stop line as the output message /traffic_waypoint.

**Comment by meenunat** [comment]
Code completed and merged with master. This issue can be closed.
