### ISSUE TITLE
DBW: Implement final throttle and brake rate limits or filtering to guarantee smooth actuation

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#50]
Apply some final rate limits or low-pass filtering to the throttle and brake commands to guarantee smooth actuation.  Check that this limiting doesn't add too much lag to the control response in the simulation.

**Comment by dinoboy197** [comment]
I had already started working on this a couple of days back :)

**Comment by edufford** [comment]
Implemented and merged, this issue can be closed.
