### ISSUE TITLE
DBW: Check final DBW control against Udacity actual drive bag data

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#51]
Check final DBW control output behavior against Udacity actual drive bag data to confirm DBW's output would be similar in scale and response to the same twist commands that their bag data issued.  The control mode of the brake might be different (percentage vs torque mode), but should translate to the same scale with Dataspeed's brake actuator mapping.

**Comment by dinoboy197** [comment]
Some very very early results here. Latest code from branch `edufford_dbw_tweaks` works well in simulator but throttle actuation is much less than Udacity data.

I've tested increases in the velocity PID controller (0.2, 0.3, 0.4) and moving to 0.3 seems to optimize (minimize) the number of timesteps where the absolute value of the difference between bag and actual throttle is greater than 0.1.

I'm not ready to make any adjustments yet, this is just one particular observation.

I've also noticed that some of the bag throttle values are unexpected (jerky jump from 0 -> 30% throttle without ramp up, etc)

**Comment by edufford** [comment]
Yea, something seems strange about the aggressiveness of their throttle control.  One thing I noticed in their bag signals is that there are topics called `filtered_accel` and `req_accel` which makes me suspect that they were using Dataspeed's built in controller to drive the car for this data.  Let me check the data a little more tomorrow morning.

**Comment by edufford** [comment]
@dinoboy197 Check my message on Slack before proceeding on this, I think we may need to find a different way to compare with the data.

**Comment by edufford** [comment]
This has been done and PID gains were adjusted in PR #72.  Closing this issue.
