### ISSUE TITLE
DBW: Max guards from walkthrough video

### ISSUE THREAD

**Issue by edufford** [team-fusionx/CarND-Capstone#94]
After reviewing the walkthrough videos again, I realized that we may need to set the max guards for throttle and braking based on their values to make sure the control stays in reasonable range for their tests.

It looks like they applied a throttle max guard of 0.2, and also used the `max_deceleration` parameter to guard the brake torque.  The `max_deceleration` parameter is set to -5 m/s^2 for styx and -1 m/s^2 for site in the launch files.

I'm not sure if we have to use these same values, but maybe it's better just to be sure.  This will have some restrictions on the simulator highway track, but I think it will still be able to drive reasonably well.  It also helps prevent the throttle from going WOT in case of toggling dbw_enabled OFF while target speed is high, and then stopping the car manually and then re-enabling it.

**Comment by dinoboy197** [comment]
I can see where these m/s^2 limits are applied in the walkthrough video, though the code in the walkthrough is working specifically with computed accelerations and decelerations, where we elected to bypass that and compute throttle and braking values directly, then apply a LPF.

It would be easy enough to compute the maximum braking force in Nm from the desired maximum deceleration value, but computing the maximum throttle in pedal value [0,1] from m/s^2 isn't quite as straightforward. Do you have a suggestion for how to map requested maximum acceleration in m/s^2 into maximum pedal value [0,1]?

**Comment by edufford** [comment]
Their code treats the velocity error as a computed accel/decel, but I don't think this is correct because the error is actually (m/s)/0.02s and they didn't account for the cycle rate.  They did apply the vehicle mass and wheel radius as an effective P gain on the error for calculating the brake torque, so the decel_limit was just actually a velocity error guard.  We could try this approach, and maybe fix the decel rate calculation to account for the cycle time, but I'm not sure if it will work well.

For the throttle, I think we should just stick with the arbitrary 0.2 max guard and disregard the accel_limit parameter like they did.  I tried a test using the accel_limit as a way to rate limit the target velocity increase rate to see if that would also help slow down the initial throttle apply starting from 0 speed, but it didn't work because of our brake/throttle blending and it also excessively limited the speed up so it couldn't keep up with the JMT target profile speed which is already smoothed to target a reasonable accel limit.

**Comment by edufford** [comment]
Oh, we should also probably set the brake controller max guard to 3250 Nm to match the Dataspeed documentation, as an extra safeguard.

**Comment by edufford** [comment]
If we apply a fixed max throttle guard, maybe it could be a parameter that is split by the launch files so that we can set 0.2 for the site test and something higher or 1.0 for the simulation.

**Comment by edufford** [comment]
This has been implemented, closing the issue.
